#!/bin/bash

sudo -v # ask for a password at the start

brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask

brew install brew-cask
brew install git
brew install git-flow
brew install heroku-toolbelt
brew install memcached
brew install libmemcached
brew install mongodb
brew install mysql
brew install node
brew install phantomjs
brew install tree
brew install vim
sudo mv /usr/bin/vim /usr/bin/vim72
brew install watch
brew install wget
brew install zeromq

brew cask install alfred
brew cask alfred link

# Applications
# Search tool -> http://caskroom.io
brew cask install adobe-creative-cloud
brew cask install arduino
brew cask install bartender
brew cask install bbc-iplayer-downloads
brew cask install brackets
brew cask install cloud
brew cask install codebug
brew cask install codekit
# Coderunner
brew cask install crashplan
brew cask install daisydisk
# brew cask instill diskmaker-x
brew cask install dropbox
brew cask install firefox
# Garmin ANT Agent
brew cask install github
brew cask install google-chrome
brew cask install google-drive
brew cask install gpgtools
brew cask install hipchat
# inSSIDer
brew cask install istat-menus
brew cask install iterm2
brew cask install jewelrybox
brew cask install kaleidoscope
brew cask install mou
brew cask install navicat-premium
# Patterns
#brew cask install postgres
brew cask install phpstorm
brew cask install pycharm
#brew cask install rstudio
# RubyMine
brew cask install skype
brew cask install spotify
# Sublime Text 3 (Current repo is 2.0.2)
brew cask install tower
brew cask install transmit
brew cask install vagrant
brew cask install versions
brew cask install viscosity
brew cask install virtualbox
brew cask install vmware-fusion

brew cask cleanup

